export const events=[
    {
        id:"1",
        headerTitle:" Mazatlán, Sin. ",
        title:"Legion RG - La Malinche - Mazatlán, Sin. ",
        location:"La Malinche",
        hour:"08:00pm",
        date:"27 ",
        month:"Abr",

        clasifitacion:"+18",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/tyeohl3xshu0i3oxsgjr",
    },
    {
        id:"2",
        headerTitle:"Cancún, Q.R.",
        title:"Beach Bash - Playa Delfines - Cancún, Q.R.",
        location:"Playa Delfines",
        hour:"09:30pm",
        date:"30 ",
        month:"Abr",

        clasifitacion:"+21",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/cr38hh1nvnpr95dgzet8",
    },
    {
        id:"3",
        headerTitle:"Guadalajara, Jal.",
        title:"Electro Fest - Estadio Akron - Guadalajara, Jal.",
        location:"Estadio Akron",
        hour:"10:00pm",
        date:"05 ",
        month:"May",

        clasifitacion:"+20",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/f6faxcmkpfxoheb3bedx",
    },
    {
        id:"4",
        headerTitle:"Puerto Vallarta, Jal.",
        title:"Salsa Night - Malecón - Puerto Vallarta, Jal.",
        location:"Malecón",
        hour:"07:30pm",
        date:"10 ",
        month:"May",

        clasifitacion:"+18",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/pkvyvm8abk75yjitgktx",
    },
    {
        id:"5",
        headerTitle:"Tulum, Q.R.",
        title:"Jungle Party - Tulum Ruins - Tulum, Q.R.",
        location:"Tulum Ruins",
        hour:"11:00pm",
        date:"15 ",
        month:"May",

        clasifitacion:"+21",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/kzruhmmfldwtah9qjqky",
    },
    {
        id:"6",
        headerTitle:"Monterrey, N.L.",
        title:"Rock Fest - Parque Fundidora - Monterrey, N.L.",
        location:"Parque Fundidora",
        hour:"08:30pm",
        date:"20 ",
        month:"May",

        clasifitacion:"+19",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/nzraz0sziskxebsb825f",
    },
    {
        id:"7",
        headerTitle:"Acapulco, Gro.",
        title:"Beach Volleyball - Playa Condesa - Acapulco, Gro.",
        location:"Playa Condesa",
        hour:"06:00pm",
        date:"25 ",
        month:"May",
        clasifitacion:"+16",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/kd7mlzruefcujankribd",
    },
    {
        id:"8",
        headerTitle:"Oaxaca, Oax.",
        title:"Mezcal Festival - Zócalo de Oaxaca - Oaxaca, Oax.",
        location:"Zócalo de Oaxaca",
        hour:"06:30pm",
        date:"02 ",
        month:"Jun",

        clasifitacion:"+18",
        image:"https://res.cloudinary.com/dsmiexs43/image/upload/f_auto,q_auto/v1/challengue-grid-baner/cr38hh1nvnpr95dgzet8",
    }
]